### ISSUE TITLE
Current Node.JS versions for Travis

### ISSUE THREAD

**Issue by marttinen** [SteveBrandt/gulp-css-scala#4]
Use LTS `4.x`, `6.x` and current version `7.x` of Node.JS for travis build.

Reference: https://github.com/nodejs/LTS#lts-schedule

**Comment by SteveBrandt** [comment]
What is wrong on the existing travis config?

`language: node_js node_js: - "iojs" - "7" - "6" - "5" - "4"`

**Comment by marttinen** [comment]
Err, I could swear it was only v4 and v5 ...
